title: Government Developer Portal

email: johnson_koh@tech.gov.sg

description: Extend Government's Potential

baseurl: ""

url: "https://developer.gov.sg"

last_updated: 5 June 2018

markdown: kramdown

plugins:
  - jekyll-assets
  - jekyll-seo-tag

breadcrumbs:
  root:
    hide: false
    image: false # Show image or title text

assets:
  sources:
    - fonts

include:

exclude:
  - functions
  - lambda
  - node_modules
  - scripts
  - src
  - Dockerfile
  - Gemfile*
  - Gruntfile.js
  - netlify.toml
  - package*.json
  - webpack.config.js

collections_dir: components

collections:
  general:
    permalink: /products/
    output: true
  sections:
    permalink: /products/:path/
    output: true
  analytics:
    permalink: /products/analytics/:path/
    output: true
  blockchain:
    permalink: /products/blockchain/:path/
    output: true
  business-application:
    permalink: /products/business-application/:path/
    output: true
  chatbot:
    permalink: /products/chatbot/:path/
    output: true
  ci-cd-ct:
    permalink: /products/ci-cd-ct/:path/
    output: true
  content-management:
    permalink: /products/content-management/:path/
    output: true
  data-sharing:
    permalink: /products/data-sharing/:path/
    output: true
  design:
    permalink: /products/design/:path/
    output: true
  grants:
    permalink: /products/grants/:path/
    output: true
  hosting:
    permalink: /products/hosting/:path/
    output: true
  identity-management:
    permalink: /products/identity-management/:path/
    output: true
  marketplaces:
    permalink: /products/marketplaces/:path/
    output: true
  security:
    permalink: /products/security/:path/
    output: true