# All config variables accessible in 'site' object, e.g. site.timezone
timezone: Asia/Singapore

# SEO; see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: developer.gov.sg
description: Resources for building Singapore Government digital products
url: "https://www.developer.gov.sg"
logo: /assets/img/logo_developer.gov.sg.png

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:
  - functions
  - lambda
  - node_modules
  - scripts
  - apps/src
  - Dockerfile
  - Gemfile*
  - Gruntfile.js
  - netlify.toml
  - package*.json
  - webpack.config.js

collections_dir: collections

collections:
  technologies:
    output: yes
  guidelines:
    output: yes
  gigs:
    output: yes
