[build]
  command = "npm run deploy"
  publish = "_site/"

[dev]
  command = "npm run dev:jekyll"

[[redirects]]
  from = "https://developer-gov-sg.netlify.com/*"
  to = "https://www.developer.gov.sg/:splat"
  status = 301
  force = true