[build]
  command = "npm run deploy"
  publish = "_site/"
  functions = "functions"

[dev]
  command = "npm run dev:jekyll"

[context.deploy-preview.environment]
  GITHUB_APP_KEY="hidden"
  GITHUB_SSO_ID="hidden"
  GITHUB_SSO_SECRET="hidden"
  GITHUB_SSO_TOKEN_HASH="hidden"
  OTP_SERVICE_APP_ID="hidden"
  OTP_SERVICE_APP_SECRET="hidden"
  GA_ID="dummy"
  HJ_ID="dummy"

[context.branch-deploy.environment]
  GITHUB_APP_KEY="hidden"
  GITHUB_SSO_ID="hidden"
  GITHUB_SSO_SECRET="hidden"
  GITHUB_SSO_TOKEN_HASH="hidden"
  OTP_SERVICE_APP_ID="hidden"
  OTP_SERVICE_APP_SECRET="hidden"
  GA_ID="dummy"
  HJ_ID="dummy"